---

- name: Ensure application directory exists
  file:
    path: "{{ application_dir }}"
    owner: "{{ application_user }}"
    group: "{{ application_group }}"
    state: directory
    mode: '755'

- name: Ensure recursive directory permissions
  file:
    path: "{{ application_dir }}"
    recurse: yes
    owner: "{{ application_user }}"
    group: "{{ application_group }}"
    state: directory


- name: Ensure log directory exists
  file:
    path: "{{ application_log_dir }}"
    owner: "{{ application_user }}"
    group: "{{ application_group }}"
    state: directory

- name: Ensure log directory permissions
  file:
    path: "{{ application_log_dir }}"
    recurse: yes
    owner: "{{ application_user }}"
    group: "{{ application_group }}"
    state: directory

- name: Ensure celery directory exists
  file:
    path: "{{ celery_dir }}"
    owner: "{{ application_user }}"
    group: "{{ application_group }}"
    state: directory
    mode: '755'
  tags: setup_celery

- name: Ensure celery recursive directory permissions
  file:
    path: "{{ celery_dir }}"
    recurse: yes
    owner: "{{ application_user }}"
    group: "{{ application_group }}"
    state: directory
  tags: setup_celery

- name: Ensure celery log directory exists
  file:
    path: "{{ application_log_dir }}/celery"
    owner: "{{ application_user }}"
    group: "{{ application_group }}"
    state: directory
    mode: '755'
  tags: setup_celery