---

- name: Ensure server stopped
  service:
    name: "{{application_name}}_appserver.service"
    enabled: true
    state: stopped
  tags: deploy-appserver

- name: Copy appserver jar file
  copy:
    src: "{{application_zip_path}}/{{application_zip_file_name}}"
    dest: "{{ application_dir }}/budget-planner-server.jar"
    owner: "{{ application_user }}"
    group: "{{ application_group }}"
    mode: 0755
  tags: deploy-appserver

- name: Ensure server started
  service:
    name: "{{application_name}}_appserver.service"
    enabled: true
    state: started
  tags: deploy-appserver
